services:
  front:
    build:
      context: ./logical-tasks-web
    ports:
      - 3000:3000


  back:
    build:
      context: ./logical-tasks-back
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/logical_tasks
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./src/main/java

  db:
    image: postgres
    user: postgres
    environment:
      - POSTGRES_DB=logical_tasks
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5